name: Email Step Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3003822@ds.study.iitm.ac.in
        run: echo "Hello, world! This is a GitHub Action test."
